name: chat_gpt_clone

services:
  rails-app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    volumes:
      - ..:/workspaces/chat_gpt_clone:cached
    depends_on:
      selenium:
        condition: service_started

  selenium:
    image: selenium/standalone-chromium
    restart: unless-stopped